### ISSUE TITLE
Подключить кубик к шаблонам API-сервиса и консьюмера рэббита

### ISSUE THREAD

**Issue by DenisBaturinByndyusoft** [Byndyusoft/byndyusoft-dotnet-test-infrastructure#11]

**Comment by asyaflesh** [comment]
- [ ] Подключить к [byndyusoft-net-rabbitmqconsumer-template](https://github.com/Byndyusoft/byndyusoft-net-rabbitmqconsumer-template)
- [ ] Добавить в [byndyusoft-net-rabbitmqconsumer-template](https://github.com/Byndyusoft/byndyusoft-net-rabbitmqconsumer-template) тест по [гайду](https://github.com/Byndyusoft/byndyusoft-dotnet-test-infrastructure/blob/master/README.md) и тест генерирующий отчет
- [ ] Подключить к [byndyusoft-templates-api](https://github.com/Byndyusoft/byndyusoft-templates-api)
- [ ] Добавить в [byndyusoft-templates-api](https://github.com/Byndyusoft/byndyusoft-templates-api) тест по [гайду](https://github.com/Byndyusoft/byndyusoft-dotnet-test-infrastructure/blob/master/README.md) и тест генерирующий отчет
